[package]
name = "_2021_5A_3DJV_RustMLDll"
version = "0.1.0"
authors = ["Abdallah EL-HAJJAM"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
rand = "0.7.3"
